services:
  - type: web
    name: telegram-video-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg curl python3 python3-pip && \
      pip3 install yt-dlp && \
      npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
