services:
  - type: web
    name: telegram-video-bot
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg curl
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp
      chmod +x ./yt-dlp
      npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
